### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by daggerhashimoto** [shargon/Xploit#1]
Hey there, cool project, congrats.

Are you planning to provide any documentation soon?

**Comment by shargon** [comment]
Yes, i want to write a guide when i finish a stable version

**Comment by daggerhashimoto** [comment]
That's great to hear, looking forward to it!

**Comment by shargon** [comment]
+1 :+1:

**Comment by alvarodh5** [comment]
You can check this "pre-wiki": https://github.com/shargon/Xploit/blob/master/README.md

If you need more help, can say us.
